PR: sincronizando fork
cacic-fct/site-secompp-2022 pull request #5
Opened 2022-08-20 21:46 UTC by Igor-MPereira

2022-08-20 21:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cacic-fct/site-secompp-2022?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cacic-fct/site-secompp-2022?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cacic-fct/site-secompp-2022?pullRequest=5) it.</sub>

2022-08-21 00:17 UTC, Yudi requested changes

2022-08-21 00:17 UTC, Yudi commented on src/lib/styles/global.scss
> +@import url('https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css');
Utilizar o pacote [metonym/svelte-bootstrap-icons](https://github.com/metonym/svelte-bootstrap-icons)
`npm i svelte-bootstrap-icons`

2022-08-21 00:17 UTC, Yudi commented on src/routes/index-components/footer.svelte
> +          &nbsp;
Margin ou padding ao invés de whitespace
<img width="435" alt="image" src="https://user-images.githubusercontent.com/12040397/185769529-3a23179a-0420-4777-9f4d-274f3d0523bc.png">

2022-08-21 00:17 UTC, Yudi commented on src/routes/index-components/header.svelte
>        <a
Seria possível/melhor utilizar `<Button>` ao invés de `<a>`, para economizar no CSS?

2022-08-21 00:17 UTC, Yudi commented on src/routes/index-components/header.svelte
> +    padding-top: 50px
Indentação incorreta, utilizar chaves {} para evitar isso

2022-08-21 00:17 UTC, Yudi commented on src/routes/index-components/nav.svelte
> +<style lang="sass">
```suggestion
<style lang="scss">
```

2022-08-21 00:17 UTC, Yudi commented on src/routes/index-components/header.svelte
> +      <!-- TODO: Alterar cor-->
```suggestion
```

2022-08-21 00:17 UTC, Yudi commented on src/routes/index-components/about.svelte
> +<style lang="sass">
```suggestion
<style lang="scss">
```

2022-08-21 00:17 UTC, Yudi commented on src/routes/index-components/footer.svelte
> +<style lang="sass">
```suggestion
<style lang="scss">
```

2022-08-21 00:17 UTC, Yudi commented on src/routes/index-components/header.svelte
> +<style lang="sass">
```suggestion
<style lang="scss">
```

2022-08-21 00:17 UTC, Yudi commented on src/routes/index-components/footer.svelte
> +          <a role="button" href="mailto:dmc@fct.unesp.br?subject=SECOMPP-2022">
```suggestion
          <a role="button" href="mailto:cacic.fct@unesp.br?subject=Contato SECOMPP22">
```

2022-08-21 00:17 UTC, Yudi commented
Ótimo trabalho com o CSS :-)

2022-08-21 00:19 UTC, Yudi commented
> [![CLA assistant check](https://camo.githubusercontent.com/4c970efeed75dd01f6778bf7e33dec85e4171375cb69acb0927bfc9d437d78d9/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/cacic-fct/site-secompp-2022?pullRequest=5) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cacic-fct/site-secompp-2022?pullRequest=5) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cacic-fct/site-secompp-2022?pullRequest=5) it.

@Igor-MPereira @ViniCastilho por favor, [assinem os termos de contribuição](https://cla-assistant.io/cacic-fct/site-secompp-2022?pullRequest=5).

2022-08-22 04:27 UTC, merged

2022-08-22 05:51 UTC, Igor-MPereira commented
Fiz os ajustes pedidos